### PR TITLE
Add FishGlob_data

### PR DESCRIPTION
**Pull request by Ly0n**
**Insert URLs to the project here:**      
https://github.com/AquaAuma/FishGlob_data

- [x] The projects is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).

_All issues labeled as 'Good First Issue' of the project listed on OpenSustain.tech will be visible on [ClimateTriage.com](https://climatetriage.com/). This is a great way to welcome new community members to your project._

### CODE REVIEW

**Review by andrew — APPROVED** [review]

**Review by andrew — CHANGES_REQUESTED** [review]
I couldn't find a license for this?

**Comment by Ly0n** [comment]
The DOI has the licence: https://zenodo.org/records/10218308

**Review by andrew — APPROVED** [review]

**Comment by Ly0n** [comment]
@AquaAuma @jepa

**Comment by AquaAuma** [comment]
thanks for adding us, do you need anything from our team?

**Comment by Ly0n** [comment]
@AquaAuma No, nothing needed. If you know more projects or maybe topics that are missing your are very welcome to give some hints or pull requests. 

I would recommend you add a LICENSE file to the repo so that people see that your projects are Creative Commons Attribution 4.0 International. Right now, most people who see your projects on GitHub might think that reuse is not allowed.

**Comment by AquaAuma** [comment]
thank you for this, the license is now added to the repository.

**Pull request merged**
