### PR TITLE
Added GridSingularityD3A

### PR DESCRIPTION
**Pull request by hannesdiedrich**
Our backend code can be cloned on github https://github.com/gridsingularity/d3a 

We have an open, accessible community slack space: https://gsycommunity.slack.com/ where everybody is invited to contribute and ask questions, may it be regarding the topic of energy exchanges or questions regarding the code or feature requests. We also accept feature request via github (see our contribution guidelines: https://github.com/gridsingularity/d3a/blob/master/CONTRIBUTING.md )

We have an up-to-date wiki for the general concepts as well as for the backend code: https://gridsingularity.github.io/d3a/d3a-documentation/

Our backend code is open source under GLPv3.0 license https://github.com/gridsingularity/d3a/blob/master/LICENSE 

Our project is awesome, because we enable energy consumers and producers to trade energy with each other in local energy exchanges in our mission to revolutionise the distribution of energy and move towards a greener and decentralised future. Users can model their energy communities, simulate, optimise and (coming soon) download and deploy their grid-aware energy exchanges.

### CODE REVIEW

**Comment by Ly0n** [comment]
Thank you so much. I'm looking at the moment your video. A great project that fits perfectly to the list. We will also change the link to the Git Repo project. We  do this so that we can quickly check in the future if a project is still ongoing and active. Unfortunately, there are many OS projects that stop activity after a few months. In this way we can keep the list clear and useful in the long term.

One hint: The certificate from your website is no longer up to date.

**Comment by tjarkdoering** [comment]
Thank you as well for your contribution! Your project is now on the list. The link goes now to the github site and I added a full stop to your entry. I hope this was okay for you.

**Comment by hannesdiedrich** [comment]
Thank you very much for adding our project to your list @tjarkdoering @Ly0n !

**Comment by hannesdiedrich** [comment]
> One hint: The certificate from your website is no longer up to date.

@Ly0n Can you please specify which page you mean? I just checked, the d3a.io and gridsingularity.com pages correctly reroute to https and the certificates are valid. Thanks in advance!

**Pull request merged**
