### PR TITLE
Add e-mission

### PR DESCRIPTION
**Pull request by Ly0n**
**Insert URLs to the project here:**      
https://github.com/e-mission/e-mission-phone

- [x] The projects is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).

_All issues labeled as 'Good First Issue' of the project listed on OpenSustain.tech will be visible on [ClimateTriage.com](https://climatetriage.com/). This is a great way to welcome new community members to your project._

### CODE REVIEW

**Review by andrew — APPROVED** [review]

**Comment by Ly0n** [comment]
@shankari @joshzarrabi @nataliejschultz

**Comment by shankari** [comment]
Thanks for the link @andrew  and @Ly0n!
Couple of notes:
- `e-mission-phone` is one repo in a fairly complex platform/framework for collecting human mobility data. The other repos are in the e-mission organization (https://github.com/e-mission), any deployer of the phone will need at least the server repo (`e-mission-server`) as well
- I am not sure why you tagged @joshzarrabi here. Josh worked on openpath several years ago, but has now moved on. The recent heavy contributors to the phone repo are @JGreenlee and @Abby-Wheelis

Screenshot 2024-05-11 at 12 12 28 PM

**Comment by Ly0n** [comment]
Thanks @shankari for your feedback. At the moment we are only listing git URLs but I have to discuss with @andrew if namespaces are also an option when projects own a complete namespace. This would allow us to list multiple repos with a single link.

Sorry for the wrong mentioning. I picked the people from the server repo. 

One feedback on your documentation. Via GitHub it is almost impossible to find your project because your do not have any topics and the goal of the project is only visible on the website. It might be interesting for you to add to the namespace descition oder zu den Projekte eine kurzen Satz, was das Ziel des Projektes ist. We listed your with "Enables people to track their travel modes—by car, bus, bike or walking and measure their associated energy use and carbon footprint."

**Comment by shankari** [comment]
Thank you for the feedback! I am generally bad at marketing and always fill out the minimal information 😶‍🌫️ 
I have now added this and filled out/updated other elements of the org profile as well!

**Comment by Ly0n** [comment]
@shankari You're not the only one. Nevertheless, your project seems to have been a success. However, I can tell you a thing or two about how extraordinary high-quality open source projects have failed simply because no one was interested in doing marketing ^^.

**Pull request merged**
