### PR TITLE
Reclustering Energy Systems

### PR DESCRIPTION
**Pull request by lappemic**
This PR addresses the reclustering of the broad category `Energy Systems` as disussed with @Ly0n.  This is a WIP an will further be refined and asked for review. Leaving it here for transparency and inputs on the process.

Approach is the same as mentioned in #695: Chatgpt provided the clustering idea and then assign the projects by hand to the new categories.

Categories to be refined:
- Energy Systems
  - [ ] Energy Modeling and Optimization (EDIT: Decided not to recluster in [this comment](https://github.com/protontypes/open-sustainable-technology/pull/696#issuecomment-2236018337)
  - [x] Energy Distribution and Grids
  - [x] Energy Monitoring and Management
  - [x] Energy System Data Access

I will update the progress here and ask for proper review once i finished from my side the first iteration.

### CODE REVIEW

**Comment by Ly0n** [comment]
@lappemic Looks great! An important note: The names of the subcategories should be separable from the other subcategories even without knowing the category.  Otherwise it will look weird in plots later on. So I would suggest 'Energy Data Accessibility and Integration' as an alternative to 'Data Accessibility and Integration'.

**Comment by Ly0n** [comment]
I have just tried to cluster the energy models using ChatGPT. The results are not very good. I see two reasons for this:

1. Many models are very different in terms of technology, methodology or geographical coverage. Some mix several types of models with each other.
2. I did a bit of research. It looks like the terminology of how to classify energy models varies a lot.

Here sources that show how clustering of projects could work:

1.
Bottom-up optimisation: MARKAL, TIMES, Calliope, DNE21+
Bottom-up accounting: LEAP, Green-X
Top-down Simulation-based: DTI energy model
Hybrid models: POLES, IEA-WEM, PROMETHEUS
Partial equilibrium: GCAM, TIAM-ECN, AIM-Enduse
Hybrid-market equilibrium: PRIMES, NEMS
Electricity models: OSEMOSYS, WASP 
Source: https://prod5.assets-cdn.io/event/6546/assets/8364062855-e70bebb6a8.pdf

2.
This is probably the best source as it is a community effort: 
https://wiki.openmod-initiative.org/wiki/Open_Models 

3.
Asking ChatGPT "How can energy models be classified? " also gives some interesting feedback.

**Comment by lappemic** [comment]
I honestly encountered the same issue as you. This is why i started with `Energy System Data Access`. 😄 

To your sources:
1. Seems not really reliable to me (Energy Modelling Platform for Europe seems to be an EU top down approach and not well acknowledged - once more)
2. Seems to be the best resource atm. Community effort and seems acknowledged (referenced in [wikipedia](https://en.wikipedia.org/wiki/Energy_modeling)) - Although they state "Currently, the models listed classify exclusively as bottom-up, ..." which btw also is stated this way on the [wikipedia page of Open Energy System Models](https://en.wikipedia.org/wiki/Open_energy_system_models).

This leads me to the conclusion that there is somehow not a proper classification... 

EDIT:
But just also found the [wikipage of Energy Modelling](https://en.wikipedia.org/wiki/Energy_modeling) which mentions more or less the categories in source 1. So my proposal is to 
1. go either with the ones from this wikipage. This would be:
  - Electricity sector models
  - Energy System Models - Top-Down Partial Equilibrium
  - Energy System Models - Top-Down General Equilibrium
  - Energy system models - Bottom-Up
  - Energy system models - Hybrid
 
Or 
2. we leave this one atm as it is and just recluster the others. 

I lean towards 2. Because it seems like lots of work and lots of confusion potential in here. WDYT?

**Comment by Ly0n** [comment]
I agree with you. We need an expert in this field to classify it. Similar to climate models, there is simply no globally accepted taxonomy that can be applied to all projects. But maybe we can change the title to just Energy System Modeling.

**Pull request merged**
