### PR TITLE
Adding Berkeley Lab Building Performance Database to Data Catalogs and Interfaces

### PR DESCRIPTION
**Pull request by Zhenev**
Hi! I was referred to this database, and since I couldn't find it on the list, I suggest adding it. I am not affiliated.

**URLs to the project:**      
https://buildings.lbl.gov/cbs/bpd

According to their site:

"The BPD contains information for over 1 million commercial and residential buildings. Fields include location (city, state, ZIP, climate zone), floor area and primary use type, operational characteristics (operating hours and number of occupants), systems level data (lighting, heating, and cooling types), certifications (ENERGY STAR, LEED, etc.), and more. For the full list of fields, refer to the [API documentation](https://buildings.lbl.gov/cbs/bpd-api-documentation/). Data availability depends on location and building type, but in general, most buildings have location, type, and energy use data, while few buildings have operational, systems, or certifications data."

More information can be found via the link I have provided.

### CODE REVIEW

**Comment by Zhenev** [comment]
Hi @Ly0n! Is there anything to be fixed about this PR? I though I'd better ask, since it's been open for a while.

**Comment by Zhenev** [comment]
Hi @Ly0n! These must have been busy days for the team, I would just appreciate hearing about the plan regarding this PR.

Good luck!

**Comment by Ly0n** [comment]
Dear @Zhenev,

sorry for not replying. The project is in a very critical phase right now, as the report was just published together with Linux Foundation about all listed projects. 

This pull request is not so easy to review and I wanted to take enough time to review it because I see the value of this project. Here's why:

 The [Contribution Guide](https://github.com/protontypes/open-sustainable-technology/blob/main/CONTRIBUTING.md) requires that large portions of projects be released under an open source license. This is necessary so that some institution can't just abandon a project. Contributors and users can be sure that such a project can always be developed further if needed. So far I could not find an open repository with an open license that allows contributions.

Another important aspect is activity. If a project has an open repository, it is much easier for me to check if a project is active and used by others (you can see this on external issues).

Another important aspect is activity. If a project has an open repository history, it is much easier for me to check if a project is active and used by others (you can see that in external issues). 

Another aspect of why I really try to list only repositories is that we are doing a study of all projects. From Git repositories, we can always automatically update the project metadata and check if it is still active. For projects not listed in Git, we have to do this manually and I try to avoid this at all costs as it is very time consuming. 

So I have to ask:
1. what is the license for the platform?
2. is the project still active?
3. do you know of an open repository that we can use for the listing?

Please excuse me for being so meticulous here but the value in this project lies in its very high data quality. I would be really happy about further contributions from you and hope you understand my argumentation.

**Comment by Zhenev** [comment]
Dear @Ly0n,

Congratulations on the publication of the report!

Completely understandable! I haven't been able to find the license agreement either. If I understand correctly, this project was [funded by the U.S. Department of Energy](https://www.energy.gov/eere/buildings/building-performance-database-bpd), with Lawrence Berkeley National Lab being [one of the contractors](https://www.energy.gov/eere/buildings/about-building-performance-database). The DOE continues to maintain the database, and they state that they accept data contributions. The data can be accessed with credentials, and there is no open repository available.

So, upon closer inspection, it seems that this source is based on a narrower definition of openness and cannot be added to your project. Sorry it required your time given your load.

I hope I'll be able to further contribute according to the criteria you listed in the future.

Best of success to you and the team!

**Comment by Ly0n** [comment]
Thank you for your feedback and further research. I am really trying to keep this website up to date, however I desperately need support from people like you. That's why I would be very happy to receive further pull requests from you.

**Pull request closed without merging**
