### PR TITLE
Add pyELQ

### PR DESCRIPTION
**Pull request by Ly0n**
**Insert URLs to the project here:**      
https://github.com/sede-open/pyELQ

- [x] The projects is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).

_All issues labeled as 'Good First Issue' of the project listed on OpenSustain.tech will be visible on [ClimateTriage.com](https://climatetriage.com/). This is a great way to welcome new community members to your project._

### CODE REVIEW

**Review by andrew — APPROVED** [review]
I didn't expect to see you submitting a Shell project!

**Comment by Ly0n** [comment]
It was a difficult consideration, but this project is about finding methane leaks, and that's a very critical issue for the climate. I personally think that supporting the fuel industry in their open data and open source approaches to work with scientists and the public is one of the lowest hanging fruits for understanding, reducing and tracking emissions where we cannot avoid them at the moment.

**Comment by Ly0n** [comment]
@bvandekerkhof

**Comment by bvandekerkhof** [comment]
Thanks for adding our project to your directory! Hoping it will lead to a wider collaboration in the open source domain!!

**Pull request merged**
