### PR TITLE
Add Climatematch Academy

### PR DESCRIPTION
**Pull request by Ly0n**
**Insert URLs to the project here:**     
https://academy.climatematch.io/ 
https://github.com/ClimateMatchAcademy/course-content

**In one sentence, explain what the project is about:**   
A wide-reaching, inclusive and approachable program aimed to introduce computational methods for climate science.

- [x] The projects is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).

### CODE REVIEW

**Comment by andrew** [comment]
Lots of broken links in their readme

**Comment by Ly0n** [comment]
Yes, I know. Had had to google for the deployed website, but the content is really great!

**Comment by Ly0n** [comment]
I created a PR to fix this: https://github.com/ClimateMatchAcademy/course-content/pull/276

**Comment by Ly0n** [comment]
It look like this project is maintained in a fork: https://github.com/neuromatch/climate-course-content

**Comment by Ly0n** [comment]
Links and content is now be updated here: https://github.com/neuromatch/climate-course-content

**Comment by Ly0n** [comment]
@nsea-log @iamzoltan @WesleyTheGeolien @jlpearso

**Comment by iamzoltan** [comment]
@Ly0n thanks :)

**Pull request merged**
