### PR TITLE
add the FlexMeasures project

### PR DESCRIPTION
**Pull request by nhoening**
Adding the FlexMeasures platform, which allows energy service companies (ESCos) to add energy flexibility services to their stack.
FlexMeasures acts as a data science backend, where forecasting and optimized intra-day planning can be run and the results are available through an API. Some basic forecasting & scheduling algorithms are built-in, we'll soon make it possible to plugin custom ones.

Read more on http://flexmeasures.readthedocs.org

My Tweet: A platform for building #energyflexibility services with forecasting and scheduling, written in Python & offering an API inspired by @USEFsmartenergy.

### CODE REVIEW

**Comment by Ly0n** [comment]
Thank you very much. A very interesting project. Fits perfectly on the list.

**Comment by nhoening** [comment]
Thanks for merging. If you're still planning to tweet it, maybe you could mention @seitabv?  (account of the company originally open-sourcing the code)

**Comment by Ly0n** [comment]
Yes, I will do that tomorrow. The tweet was already created yesterday by the GitHub Action script. I will create another one tomorrow when my social media blocker will allow it again. I also want to create a post about this project on LinkedIn.

**Comment by nhoening** [comment]
Thank you. Let me know if I can help! On LinkedIn, we are https://www.linkedin.com/company/seita-smart-sustainability/

**Pull request merged**
