### PR TITLE
Add iotables

### PR DESCRIPTION
**Pull request by Ly0n**
**Insert URLs to the project here:** https://github.com/rOpenGov/iotables/

- [x] The projects is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).

_All issues labeled as **Good First Issue** of the project listed on [OpenSustain.tech](https://opensustain.tech/) will be visible on [ClimateTriage.com](https://climatetriage.com/). This is a great way to welcome new community members to your project._

All projects listed will be posted on our [Mastodon channel](https://mastodon.social/@opensustaintech)

### CODE REVIEW

**Review by andrew — APPROVED** [review]

**Comment by Ly0n** [comment]
@antaldaniel

**Comment by antaldaniel** [comment]
Hi @Ly0n it is very interesting what you are doing, because I develop open source sustainability management tools; what is unclear to me is your taxonomy to what goes into this open sustainable technology and where to place our products!

**Comment by Ly0n** [comment]
@antaldaniel This whole project started unstructured and was done by several people just for fun during a COVID lockdown. Over the years, we have broken the projects down into different categories and subcategories so that each subcategory doesn't get too small. This is more of a bottom-up approach than a top-down approach. If a new subcategory or category could be created by clustering enough projects we could find, we would create that category. 

We are currently working with various NLP approaches to improve the labeling/taxonomy of the projects based on the project READMEs. This will allow for example to show the projects based on SDGs or other taxonomies. 

If your tool should target different categories / areas, like biodiversity + climate change, we should discuss to open a new category like Local Sustainable Management or Cooperated Sustainable Management.  Such comprehensive frameworks do not exist in open source yet, but it would be good to have them. We can also have a call if you are interested to exchange ideas here in more detail.  Just send me an email: tobias.augspurger@protontypes.eu

**Comment by antaldaniel** [comment]
Hi @Ly0n I sent you an email, I work a lot with open science taxonomies and will give it a thought!

**Pull request merged**
