### PR TITLE
Add Environmental Data Science book

### PR DESCRIPTION
**Pull request by acocac**
**[Environmental Data Science book](https://github.com/alan-turing-institute/environmental-ds-book)** 

- [x] The projects is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).

_All issues labeled as **Good First Issue** of the project listed on [OpenSustain.tech](https://opensustain.tech/) will be visible on [ClimateTriage.com](https://climatetriage.com/). This is a great way to welcome new community members to your project._

All projects listed will be posted on our [Mastodon channel](https://mastodon.social/@opensustaintech)

### CODE REVIEW

**Comment by Ly0n** [comment]
@acocac Thank you for your contribution. This is truly an epic project that your community has created here. 

I was already familiar with this project, but a long time ago we decided to move the very good courses and tutorials to the Education section of this project, where Environmental Data Science book is already listed, which is unfortunately a different list. We did this to make it easier for newcomers to find entry-level projects among the hundreds of expert-level open source projects. For various reasons, we are considering moving the education projects to the main list, but this has not yet happened. One reason is that I have noticed that people simply overlook the education section. 

It would be great to get your feedback on this. Does it make sense to create a "sustainable education" section, or "education for sustainable development" as the UN calls it, under sustainable development with all the projects from the education list? @andrew @RichardLitt @joshhopkins

**Comment by joshhopkins** [comment]
This is truly a great resource. However, at the risk of becoming noisy, I think educational resources should remain seperate from tooling.

**Comment by RichardLitt** [comment]
I don't see a reason not to have a longer Markdown list with an education section. I don't know how many eyes are on the education.md file.

**Comment by acocac** [comment]
@Ly0n apologies, it was my bad that I didn't double check the education section. I suggest increasing the awareness of the education resources by including them in the Climate Triage. There's a great opportunity to promote all educational resources that are complementary to the curated list of tools. Indeed, I added the EDS book because it wasn't listed in the Triage.

I think the Education for Sustainable Development makes sense. I am a topic editor for [JOSE](https://jose.theoj.org), and there are other great examples of educational resources for environmental sustainability (see for example [1](https://jose.theoj.org/papers/10.21105/jose.00090).

@joshhopkins can you expand what do you mean by noisy? Please be aware some educational resources such as Project Pythia and EDS book have a strong investment in the community and maximise open source infrastructure to increase the visibility of open research (data, software, pipelines) in environmental sustainability. Project Pythia has solid developments for scheduling and testing the health of their foundational materials and cookbooks.

**Comment by joshhopkins** [comment]
@acocac I definitely appreciate your view on this. I mean potentially noisey, in that educational resources are so vast, that without applying normative judgments there is a risk of diluting this directory. Of course, there is often overlap between documentation and tooling, but in general, I think there should be some separation between the two with a slightly different acceptance criteria.

**Comment by acocac** [comment]
> @acocac I definitely appreciate your view on this. I mean potentially noisey, in that educational resources are so vast, that without applying normative judgments there is a risk of diluting this directory. Of course, there is often overlap between documentation and tooling, but in general, I think there should be some separation between the two with a slightly different acceptance criteria.

@joshhopkins thanks for elaborating your points on this. There's then a clear opportunity for a dedicated initiative tracking progress and foster collaboration on educational-focused open source resources in environmental sustainability. 

 👏 The climate triage is an amazing portal, I hope others can extend it to other domains!

**Comment by Ly0n** [comment]
We have to decide at the next community meeting how to deal with the educational area. Until then, I don't see a problem with including these projects on both lists. So it will also appear on ClimateTriage.

**Comment by Ly0n** [comment]
Just a small side note. This was repo #2000 we listed based on ecosyste.ms data.. :partying_face: :balloon: :rocket:

**Pull request merged**
